version: '3.1'

services:
  mongo:
    image: mongo
    container_name: TESTENV_issue-tracker_mongodb
    restart: on-failure
    command: --smallfiles
    environment:
      # REMINDER: THIS IS NOT FOR PROD
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    # This is for test environment - we don't persist anything!
    # volumes:
      # - ./test_db:/data/db
  mongo-express:
    image: mongo-express
    container_name: TESTENV_issue-tracker_mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      # REMINDER: THIS IS NOT FOR PROD
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  redis:
    image: redis
    container_name: TESTENV_issue-tracker_redis
    restart: on-failure
    ports:
      - 6379:6379
    network_mode: bridge
